import type { ThemeColors, ThemeShadows } from '../theme';
import { TYPOGRAPHY, SPACING } from '../constants';

export const createStyles = (colors: ThemeColors, _shadows: ThemeShadows) => ({
  container: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  backButton: {
    padding: SPACING.xs,
    marginRight: SPACING.md,
    minWidth: 44,
    minHeight: 44,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  headerCenter: { flex: 1 },
  headerTitle: {
    ...TYPOGRAPHY.h2,
    color: colors.text,
    fontWeight: '400' as const,
  },
  addButton: {
    padding: SPACING.sm,
    minWidth: 44,
    minHeight: 44,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  centered: {
    flex: 1,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingHorizontal: SPACING.xxl,
  },
  emptyInline: {
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingHorizontal: SPACING.xxl,
    paddingVertical: SPACING.xxl,
  },
  emptyText: {
    ...TYPOGRAPHY.h3,
    color: colors.text,
    marginTop: SPACING.md,
  },
  emptySubtext: {
    ...TYPOGRAPHY.bodySmall,
    color: colors.textMuted,
    marginTop: SPACING.xs,
    textAlign: 'center' as const,
  },
  list: { flex: 1 },
  listContent: { paddingBottom: SPACING.xxl },
  capturePanel: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  captureIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.surfaceLight,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    marginRight: SPACING.md,
  },
  captureText: {
    flex: 1,
    marginRight: SPACING.md,
  },
  captureTitle: {
    ...TYPOGRAPHY.body,
    color: colors.text,
    fontWeight: '400' as const,
  },
  captureSubtitle: {
    ...TYPOGRAPHY.bodySmall,
    color: colors.textMuted,
    marginTop: 2,
  },
  controlsPanel: {
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.background,
  },
  searchRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: SPACING.sm,
    minHeight: 42,
    paddingHorizontal: SPACING.md,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  searchInput: {
    ...TYPOGRAPHY.body,
    color: colors.text,
    flex: 1,
    paddingVertical: 0,
    minHeight: 40,
  },
  scopeFilterRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: SPACING.sm,
    marginTop: SPACING.sm,
  },
  scopeFilterButton: {
    flex: 1,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    minHeight: 44,
    paddingHorizontal: SPACING.sm,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  scopeFilterButtonActive: {
    borderColor: colors.primary,
    backgroundColor: `${colors.primary}15`,
  },
  scopeFilterText: {
    ...TYPOGRAPHY.labelSmall,
    color: colors.textMuted,
  },
  scopeFilterTextActive: {
    color: colors.primary,
    fontWeight: '400' as const,
  },
  section: {
    paddingTop: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  sectionTitle: {
    ...TYPOGRAPHY.label,
    color: colors.textMuted,
    paddingHorizontal: SPACING.lg,
    marginBottom: SPACING.xs,
    textTransform: 'uppercase' as const,
  },
  sectionTitleStandalone: {
    ...TYPOGRAPHY.label,
    color: colors.textMuted,
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.md,
    paddingBottom: SPACING.xs,
    textTransform: 'uppercase' as const,
  },
  candidateRow: {
    flexDirection: 'row' as const,
    alignItems: 'flex-start' as const,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.background,
  },
  candidateIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: colors.surfaceLight,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    marginRight: SPACING.md,
    marginTop: 2,
  },
  candidateInfo: { flex: 1 },
  candidateActions: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'flex-end' as const,
    gap: SPACING.sm,
    marginTop: SPACING.sm,
  },
  candidateActionButton: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: SPACING.xs,
    minHeight: 44,
    paddingHorizontal: SPACING.md,
    borderRadius: 8,
  },
  candidateDismissButton: { backgroundColor: colors.surfaceLight },
  candidateEditButton: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  candidateApproveButton: { backgroundColor: colors.primary },
  candidateDismissText: {
    ...TYPOGRAPHY.labelSmall,
    color: colors.textMuted,
  },
  candidateEditText: {
    ...TYPOGRAPHY.labelSmall,
    color: colors.primary,
  },
  candidateApproveText: {
    ...TYPOGRAPHY.labelSmall,
    color: colors.surface,
  },
  memoryRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  memoryIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: colors.surfaceLight,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    marginRight: SPACING.md,
  },
  memoryInfo: {
    flex: 1,
    marginRight: SPACING.sm,
  },
  memoryHeader: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: SPACING.sm,
    marginBottom: 2,
  },
  memoryTitle: {
    ...TYPOGRAPHY.body,
    color: colors.text,
    flex: 1,
  },
  memoryScope: {
    ...TYPOGRAPHY.labelSmall,
    color: colors.textMuted,
    backgroundColor: colors.surfaceLight,
    paddingHorizontal: SPACING.sm,
    paddingVertical: 2,
    borderRadius: 8,
    overflow: 'hidden' as const,
  },
  memoryBody: {
    ...TYPOGRAPHY.bodySmall,
    color: colors.textSecondary,
  },
  memoryMeta: {
    ...TYPOGRAPHY.labelSmall,
    color: colors.textMuted,
    marginTop: 3,
  },
  deleteButton: {
    padding: SPACING.sm,
    marginLeft: SPACING.sm,
    minWidth: 44,
    minHeight: 44,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
});
